# Generated by Django 5.2.17 on 2026-08-11 21:46

import django.db.models.deletion
import studio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_validation_and_notification_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at']},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-starts_at', '-created_at'], 'verbose_name': 'запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['order', 'id'], 'verbose_name': 'работа', 'verbose_name_plural': 'Галерея'},
        ),
        migrations.AlterModelOptions(
            name='masterschedule',
            options={'ordering': ['master', 'weekday'], 'verbose_name': 'расписание', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.AlterModelOptions(
            name='mastertimeoff',
            options={'ordering': ['-starts_at'], 'verbose_name': 'блокировка', 'verbose_name_plural': 'Блокировки'},
        ),
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['order', '-date'], 'verbose_name': 'отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'title'], 'verbose_name': 'услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='specialworkingday',
            options={'verbose_name': 'особый день', 'verbose_name_plural': 'Особые дни'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', 'name'], 'verbose_name': 'мастер', 'verbose_name_plural': 'Команда'},
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='studio_book_master__5939b3_idx',
            old_name='studio_book_master__53a531_idx',
        ),
        migrations.AlterField(
            model_name='article',
            name='uploaded_image',
            field=models.ImageField(blank=True, upload_to='journal/', validators=[studio.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='booking',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='studio.service'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery/', validators=[studio.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='service',
            name='eyebrow',
            field=models.CharField(default='Услуга', max_length=80),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, upload_to='services/', validators=[studio.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=True, verbose_name='На главной'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='service',
            name='uploaded_icon',
            field=models.ImageField(blank=True, upload_to='services/', validators=[studio.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='siteasset',
            name='fallback_path',
            field=models.CharField(blank=True, max_length=200, verbose_name='Резервный static-файл'),
        ),
        migrations.AlterField(
            model_name='siteasset',
            name='file',
            field=models.ImageField(blank=True, upload_to='site/', validators=[studio.models.validate_image_size], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='siteasset',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.CharField(default='atelier.svg', max_length=120),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='slug',
            field=models.SlugField(default='master', unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='uploaded_image',
            field=models.ImageField(blank=True, upload_to='team/', validators=[studio.models.validate_image_size]),
        ),
    ]
